### PR TITLE
fix(sw): return 200-299,304 responses immediately

### LINKED ISSUE #380: feat: improve caching experience
Caching speeds slowed down slightly when adding vercel caching and fixing the fetch Error issues. 

We need to investigate if there's anything else we can do to improve speeds here.

> There seems to be a caching related performance degradation. Whenever I reload using cmd-r, all of the data is being fetched again, I think it doesn't really use the cache for me

https://github.com/pln-planning-tools/Starmap/assets/1173416/61bb3b61-1e3f-4c34-9c5f-4a69d36307f3

> I would expect CMD+R to use the cache. CMD+Shift+R should reload without cache. In the video recording above I'm simply hitting enter on the address bar

> It doesn't flash the cached content before refetching, as I described above, it just seems to never use a cache?

```[tasklist]
### Tasks
- [ ] Confirm caching is working at service-worker level (it should return response immediately if it has cache, but re-populate it's cache with a second query)
- [ ] Confirm caching is working at the vercel level (it should have cache-hit or miss value when it has or doesn't have cache)
- [ ] optimize cache-control and stale values 
```

### PR DESCRIPTION
**Pull request by SgtPooki**
fixes #380

This PR updates the caching strategy to prevent the duplicate call to the backend
if we have a cached call, and returns it immediately.

One thing to note, is that vercel-cached responses return [HTTP 304](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304) responses,
and `response.ok` didn't check for that. This PR also addresses this.

So, a call to the backend vercel function, that calls github does *NOT* happen IFF:

1. There is a cached response
2. That cached response has a status code of 200-299
3. That cached response has a status code of 304;

A backend call to the backend vercel function, that calls github, *WILL* happen IFF:

1. There is *no* cached response
2. The cached response is a failed request (github error, vercel error, etc)
3. The cached response was a modified result.
3. ~~The cached response's max-age is "too old"~~

### CODE REVIEW

**Comment by SgtPooki** [comment]
Verified that subsequent load is almost instant:

1. Load page with no cache (application data cleared)
2. data pulls fully from vercel backend cache (cached from previous attempts, so faster than fully from github, but still takes longer than when it's cached in the sw for HUGE roadmaps)
3. reload page
4. page loads almost instantaneously

Verified that cache is invalidated for updated github items (description updates):

1. load page
2. edit github issue
3. reload page (not clearing cache.. ) === github issue is not updated in starmap, but a popup appears showing new data exists
4. reload page === github issue that was stale is updated in starmap, but the rest loads very quickly
5. reload page === latest github issue data (which is cached in SW) loads instantly for everything


@whizzzkid @momack2 please review. Preview urls for the urls Molly gave in slack are:

* https://starmaps-git-380-feat-improve-caching-experience-ipfs-ignite.vercel.app/roadmap/github.com/filecoin-station/roadmap/issues/1#view=list
* https://starmaps-git-380-feat-improve-caching-experience-ipfs-ignite.vercel.app/roadmap/github.com/protocol/engres/issues/9#view=detail

File: sw/CacheChildrenStrategy.ts [hunk 1]
```diff
@@ -25,6 +30,31 @@ contentHashDB.version(1).stores({
...
+ * check if the cached response is valid:
+ * 1. Not null
+ * 2. 200-299 or 304 response
+ * 3. Not too old (not greater than MAX_SW_CACHE_AGE)
+ */
+function isCachedResponseStillValid (cachedResponse?: Response): cachedResponse is Response {
+  if (!cachedResponse) {
+    return false
+  }
+  if (!cachedResponse.ok || cachedResponse.status === 304) {
```
Comment (whizzzkid) [inline sw/CacheChildrenStrategy.ts:43]: Can merge the two if statements.

**Review by whizzzkid — APPROVED** [review]
Ok can confirm it's a bit faster, thanks @SgtPooki

File: sw/CacheChildrenStrategy.ts (hunk 1 above)
Comment (SgtPooki) [reply sw/CacheChildrenStrategy.ts:43]: Yea, i was just trying to keep them separate and explicit for clarity
